# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/kinetics/val_data_joint.npy
  label_path: ./data/kinetics/val_label.pkl
  debug: False
  argument: True


# model
model: model.sgcn.Model
model_args:
  in_channels: 5
  num_class: 400
  num_person: 2
  num_point: 18
  dropout: 0
  graph: graph.kinetics.Graph
  graph_args:
    labeling_mode: 'spatial'


# test 
phase: test
device: 0
test_batch_size: 64
weights: ./runs/ki_sgcn_joint-60-114558.pt


work_dir: ./work_dir/kinetics/sgcn_test_joint
model_saved_name: ./runs/ki_sgcn_test_joint
save_score: True