work_dir: ./work_dir/ntu/xview/sgcn_joint
model_saved_name: ./runs/ntu_cv_sgcn_joint
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/ntu/xview/train_data_joint.npy
  label_path: ./data/ntu/xview/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False
  argument: True

test_feeder_args:
  data_path: ./data/ntu/xview/val_data_joint.npy
  label_path: ./data/ntu/xview/val_label.pkl
  argument: True

# model
model: model.sgcn.Model
model_args:
  in_channels: 6
  num_class: 60
  num_point: 25
  num_person: 2
  dropout: 0.4
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [30,40]
warm_up_epoch: 0

# training
device: [ 0, 1 , 2 , 3]
batch_size: 64
test_batch_size: 64
num_epoch: 60
nesterov: True
